const moviesCards = [
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1234',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1234',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1234',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1234',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '123',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1235',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1235',
    },
    {
        country: 'USA',
        director: 'Tarantino',
        duration: 111,
        year: 2003,
        description: 'Наемная убийца жестоко мстит бывшим подельникам. Жестокий боевик Квентина Тарантино — с анимацией и отсылками',
        image: 'https://pbs.twimg.com/media/EWNpbfgWAAE_dEo.jpg',
        trailer: 'https://www.kinopoisk.ru/film/2717/?from=discovery_player',
        thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/28bca6bf-2225-4c0d-881e-8c0bff5d7188/800x800',
        owner: '60241ffae3325025449fcb24',
        nameRU: 'Убить Билла',
        nameEN: 'Kill Bill',
        movieId: '1235',
    },
]

export default moviesCards;